# Same as what poky does: must explicitly delcare the base OS

FROM crops/yocto:ubuntu-20.04-base
USER root
RUN apt-get update && \
    apt-get install -y \
        sudo \
        iptables \
        pigz \
        qemu-system && \
    rm -rf /var/lib/apt/lists/*
COPY entry.py /usr/bin
COPY sudoers /etc/sudoers
ENTRYPOINT ["/usr/bin/entry.py", "yoctouser"]
WORKDIR /

RUN adduser yoctouser sudo

# Environment variables for our build setup
ENV WRLX_ALL_LAYERS=/opt/wrlinux/LTS19
ENV SSTATE_DIR=/var/lib/sstate
ENV GPG_PATH=/tmp/gpg_path
ENV BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE SSTATE_DIR STARLAB_LAYERS GPG_PATH"
