# Same as what poky does: must explicitly delcare the base OS

FROM crops/yocto:ubuntu-18.04-base
USER root
RUN apt-get update && \
    apt-get install -y \
        qemu-system && \
    rm -rf /var/lib/apt/lists/*
COPY entry.py /usr/bin
ENTRYPOINT ["/usr/bin/entry.py"]
WORKDIR /

# Environment variables for our build setup
ENV SSTATE_DIR=/var/lib/sstate
ENV GPG_PATH=/tmp/gpg_path
ENV BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE SSTATE_DIR STARLAB_LAYERS GPG_PATH"
